services:
  postgres:
    image: postgres:14.1-alpine
    container_name: "postgres"
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres:/data/db
    ports:
      - "5433:5432"
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge

volumes:
  postgres:
