"""test migrations

Revision ID: fa6c4b5f1973
Revises: 00d68567e024
Create Date: 2023-07-19 16:42:01.318325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa6c4b5f1973'
down_revision = '00d68567e024'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
